baseurl: ""
url: "https://rosthansilva.com/"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-paginate-v2 # Plugin necessário para subpastas /pt/ e /en/
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag
  - jekyll-feed

languages: ["pt", "en"]
default_lang: "pt"

highlighter: rouge

# Configurações de SEO (jekyll-seo-tag)
social:
  name: Rosthan Silva
  links:
    - https://twitter.com/rosthanlinux
    - https://github.com/rosthanlinux
    - https://linkedin.com/in/rosthanlinux

# NOVO BLOCO: Configuração do Paginate V2
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/" # Isso vai gerar /pt/page/2/ automaticamente
  title: ":title - Page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Pages Path & Defaults
defaults:
  - scope:
      path: "" # Raiz do site
    values:
      layout: "default"
  - scope:
      path: "_pages"
    values:
      permalink: "/:basename/"

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed