#-------------------------------
# General Site Settings
title: Rosthan Silva
logo: logo.svg # You can add own logo.
description: DevOps na Prática 


#-------------------------------
# Author Settings
author:
  name: Rosthan Silva
  image: rosthan_e_valentim.png
  say-hello: Olá, Sou <strong>Rosthan Silva</strong>
  bio: Especialista em Sistemas <strong>Linux</strong>, <strong>DevOps</strong>, <strong>Arquitetura Cloud</strong>, e  <strong> Microserviços</strong>. Aqui eu compartilho um pouco de conteúdo para ajudar na experiência técnica dos meus seguidores. Meu hobby é codar com meu filho no colo, jogar souls likes e metroidvanias.

pt:
  cookie:
    message: "Este site utiliza cookies para garantir que você obtenha a melhor experiência."
    allow: "Aceitar"
    deny: "Recusar"
    link: "Saiba mais"
  title: Rosthan Silva
  description: DevOps na Prática
  author:
    say-hello: Olá, Sou <strong>Rosthan Silva</strong>
    bio: Especialista em Sistemas <strong>Linux</strong>, <strong>DevOps</strong>, <strong>Arquitetura Cloud</strong>, e <strong>Microserviços</strong>. Aqui eu compartilho um pouco de conteúdo para ajudar na experiência técnica dos meus seguidores. 
  search:
    label: "Procure no Blog"
    placeholder: "Digite aqui..." 
en:
  cookie:
    message: "This website uses cookies to ensure you get the best experience."
    allow: "Approve"
    deny: "Reject"
    link: "Learn more"
  title: Rosthan Silva
  description: DevOps in Practice
  author:
    say-hello: Hi, I'm <strong>Rosthan Silva</strong>
    bio: Specialist in <strong>Linux Systems</strong>, <strong>DevOps</strong>, <strong>Cloud Architecture</strong>, and <strong>Microservices</strong>. Here I share content to help the technical experience of my followers.
  en:
  search:
    label: "Search the Blog"
    placeholder: "Type here..."
#-------------------------------
# Contact links
twitter: https://twitter.com/rosthanlinux # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/rosthanlinux # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
linkedin: https://linkedin.com/rosthanlinux
github: https://github.com/rosthansilva

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: #mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: rosthanlinux # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
